### ISSUE TITLE
multiple language versions

### ISSUE THREAD

**Issue by YXGust** [delphidabbler/codesnip#124]
Have you considered multiple language versions?

**Comment by delphidabbler** [comment]
Hi. Sorry for the delay - I've been unwell.

Yes, I have considered it, and a few years ago made some progress in achieving it. However I never managed to finish it. I'd still like to do it, but the old code base doesn't make it easy.

After numerous attempts over 10 years, I've reluctantly decided I'll never have the time to do it.

If you want to see how far I got take a look at the `pagoda`, `pavillion` and `belvedere` branches of this repository.
