### ISSUE TITLE
Test compilation with Alexandria still not supported?

### ISSUE THREAD

**Issue by PeterPanino** [delphidabbler/codesnip#18]
With CodeSnip 4.18.0 and Delphi 11 Alexandria installed, the Delphi 11 test compilation is missing:

![image](https://user-images.githubusercontent.com/5140376/134394268-cc5ac2cd-6cba-44d7-b4d9-9a9ad045bab6.png)

**Comment by PeterPanino** [comment]
Found the "Configure Compilers" menu item:

![image](https://user-images.githubusercontent.com/5140376/134396181-b43df867-e9d1-495f-a2a6-388e02947a3e.png)

**Comment by delphidabbler** [comment]
Glad you found how to set it up.

You've given me an idea for a new feature to automatically scan for new compilers tho! See issue #19.
