### ISSUE TITLE
Add option to customise font size in detail pane

### ISSUE THREAD

**Issue by delphidabbler** [delphidabbler/codesnip#41]
Following implementation of customisable font size for overview pane tree view (see issue #7), it remains 5o allow for customisation of the font size for detail pane, as was suggested by the IP of issue #7.

**Comment by delphidabbler** [comment]
@PeterPanino - this is still on the todo list!

**Comment by delphidabbler** [comment]
Think I've worked out how to do this - needs some testing.

**Comment by PeterPanino** [comment]
I can test it for you.

**Comment by delphidabbler** [comment]
Cheers

Could sleep last night so ended up browsing source code on my tablet! Think
I know what to do now.

Peter

**Comment by delphidabbler** [comment]
The _TDetailViewFrame.BuildCSS_ method in the _FrDetailView_ unit is probably where the font size needs to be set from _Preferences_.

Need to set font size in the following CSS:

- `body`
- `table `
- `h1`
- `h2`
- `.active-text h2`
- `.snippet-list .active-text h2`
- `#newtab`

Need to give some thought to whether to simply add a constant size for larger fonts (like `h1` for e.g.) or whether to scale them up proportionately).

**Comment by delphidabbler** [comment]
Not sleeping again!

Here's some suggested code for _TDetailViewFrame.BuildCSS_ that might do the job.

Add new `ContentFont` object:

```pascal
var
  ContentFont: TFont;
  ...
begin
  ContentFont := nil;
  CSSFont := TFont.Create;
  try
    ContentFont := TFont.Create;
    TFontHelper.SetContentFont(ContentFont);
    ContentFont.Size := Preferences.xxxxx;
     ...
  finally
    ContentFont.Free;
    ...
 end;
end;
```

Then whenever we have the statement

```pascal
TFontHelper.SetContentFont(CSSFont);
```

Replace it with 

```pascal
CSSFont.Assign(ContentFont);
```

And if we decide to scale heading fonts, use something like this:

```pascal
var
  FontScaleFactor: Single;
...
begin
  ...
  FontScaleFactor  := 1.0 / ContentFont.Size;
  ...
  CSSFont.Size := CSSFont.Size + Max(
    Round(CSSFont.Size * FontScaleFactor * Increment),
    Increment
  );
  ...
end;
```

Where
* `FontScaleFactor` is the amount we increase a font size by to get proportionally the same growth as adding 1 to the default content font size.
* `Increment` is the number of point sizes the content font size was originally increased by.

**Comment by delphidabbler** [comment]
The above worked quite well, but I needed to deal with the `<code>` tags generated by the REML `<mono>` tags. They were overriding the body font size. Aargh!

**Comment by delphidabbler** [comment]
@PeterPanino I think I've done it, and would be grateful if you could test.

![codesnip-large-detail-pane fonts](https://user-images.githubusercontent.com/5164283/147915688-9adbb3ea-d97e-4754-b09d-ff74967ad1c5.png)

I've attached a copy of a special, portable, 4.19.0 build with an extra entry on Preferences | Display page for the "detail pane" font. That changes all the font sizes in the detail pane except for the source code - that can already be changed on the Syntax Highlighter page. It's not very elegant, but the preferences dialogue resisted my attempts to move the source code font sizing code to a different page - it was going to get messy.

Download [CodeSnip-Portable-Special-Build-419.zip](https://github.com/delphidabbler/codesnip/files/7801330/CodeSnip-Portable-Special-Build-419.zip)

I've sent the portable version, so you can just extract and run it to test it without it affecting your existing installation in any way. I've included a copy of the Code Snippets Database, along with a special custom test snippet (see the `_TEST` category) that contains all possible formatting options that can appear on the detail pane. The downside is that the portable version won't display your own snippets (but you can import them if you feel the need - see [this FAQ](https://github.com/delphidabbler/codesnip-faq/blob/master/UsingCodeSnip.md#faq-8)).

***BTW*** I haven't customised any fonts in the attached version - I'll leave that for you to try to ensure it works "out of the box".

Anyhow, if you find it's suitable I can release the official v4.20.0 version in a couple of days.

I'm afraid there's nothing I can do to resize the menu, status bar or dialogue boxes - I made them scalable originally but it was such a mess I turned it all off again!

I've not updated the help file yet.

Thx for offering to help.

> ***BTW2:*** If you want to poke around, the font info is stored in `AppData\User.config` under the `[Prefs:Display]` section in the `OverviewFontSize` and `DetailFontSize` keys (they'll not be present until you have run the program at least once). The source code font size is in `[Prefs:Hiliter]` under the `FontSize` key.
>
> For completeness, the Code Snippets database files are in `AppData\CSDB` and custom snippets are in `AppData\UserDB`. Last but not least, favourites are recorded in `AppData\Favourites`. The `UserData` directory is an artefact of older versions that isn't used any longer.

**Comment by delphidabbler** [comment]
Hi Peter

Not sure if GitHub notifies you direct, but I've uploaded a test version of
CodeSnip to the issue page at
https://github.com/delphidabbler/codesnip/issues/41

Be grateful if you'd check it out. Full details on the linked GitHub page
in the last comment.

Cheers

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by delphidabbler** [comment]
No response received. Assuming all is OK.
