### ISSUE TITLE
How to customize the treeview font size?

### ISSUE THREAD

**Issue by PeterPanino** [delphidabbler/codesnip#7]
It seems you forgot an option to customize the treeview font size. On High DPI monitors this is very important!

**Comment by PeterPanino** [comment]
Of course, there should also be font size customization for the additional text (e.g.  description, snippet information, ...)

**Comment by delphidabbler** [comment]
Good point. Never considered this, probably because I don't have such a beast of a monitor!

I'll have a look at how to implement this.

**Comment by delphidabbler** [comment]
Don't forget to

- [ ] update help file
- [ ] update config file docs

**Comment by delphidabbler** [comment]
Finally found a way to do this successfully!

Implemented by commit e1e8b6b

**Comment by PeterPanino** [comment]
I have downloaded the compiled version 4.18.1 from SourceForge. Where can I customize the UI font size?

**Comment by delphidabbler** [comment]
Hi Peter

You can't do it in 4.18.1.

I'm hoping to release 4.19.0 today, with luck (the aim is midnight UTC). In
that version you can customise the overview pane treeview. 4.19.0 will have
a font size combo box in the Display page of the Preferences dialogue box
(Tools | Preferences menu option).

The source code size can also be increased on the Syntax Highlighting page
of Prefs.

The rest of the main display is proving problematic to change reliably. The
code is old and creaky, largely written before high dpi monitors were even
thought of!

I'll be having another go in the new year.

The whole thing really needs a ground up rewrite.

Cheers
Peter

**Comment by delphidabbler** [comment]
v4.19.0 just uploaded.

Happy new year.

Cheers
Peter

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
