### ISSUE TITLE
IntfExternalObj.pas does not exist

### ISSUE THREAD

**Issue by PeterPanino** [delphidabbler/codesnip#93]
Hello, I downloaded CodeSnip 4.21.0 master zip file. When trying to build **CodeSnip.dpr** in Delphi 11.2, I got this error:

[dcc32 Fatal Error] CodeSnip.dpr(376): F1026 File not found: 'AutoGen\IntfExternalObj.pas'

Why is this file missing?

**Comment by delphidabbler** [comment]
That file, along with various resource files are generated by the build chain.

See [`Build.html`](https://htmlpreview.github.io/?https://github.com/delphidabbler/codesnip/blob/master/Build.html) for details.

When I get a minute I'll generate the files and post them here.

**Comment by delphidabbler** [comment]
Here's the promised files.

[build-generated-files.zip](https://github.com/delphidabbler/codesnip/files/10882490/build-generated-files.zip)

The binary files need to be placed in the Bin directory, or on the binary search path, the .pas file needs to go in Src/AutoGen directory and the .cfg file needs to go in the Src directory.

CodeSnip _might_ then build from the IDE, but I haven't tried it.

But note that the only guaranteed way to build CodeSnip from scratch is to follow the process in `Build.html`.

After doing that CodeSnip will build fine from the IDE providing you only change .pas files.

**Comment by delphidabbler** [comment]
Closing this now
